### ISSUE TITLE
history/cache of with: construction in Router.update after page refresh

### ISSUE THREAD

**Issue by p-kostic** [Profiscience/knockout-contrib#552]
**Package(s)**
 - [router]

**What I'm trying to do**
When passing the current user to `ctx` in the scenario that I want to e.g. go to a detailed user page. 
```js
    navigateToUser(user) {
      Router.update('/users/' + user.id, { with: { user } })
    }
```
How would I then subsequently ensure that this information is not lost upon a refresh of the user detail page? Of course, in the event that the user has never been to the `/users/` page, there would be no cache/context to retrieve and I'd have to initially retrieve the info for that specific user. This can be done by checking ctx.user to be undefined. 

However, in the event that it was just a simple page refresh, is there any history/ctx/cache still available?

**What I've tried**

Only the scenario in the first paragraph after the code from the readme, curious about options. They might be inapplicable to your router and maybe more related to `knockout` though, if that's not a problem.

https://github.com/spoike/knockout.persist was mentioned in [this ](https://stackoverflow.com/questions/51898258/its-possible-to-save-the-data-of-the-viewmodel-with-knockout-js-after-refresh-p) SO thread, but the repo is 7 years old.

P.S Couldn't access the Gitter @ https://gitter.im/Profiscience/knockout-contrib

**Comment by caseyWebb** [comment]
I'd generally recommend bailing to the behavior they would encounter on an initial page load so refreshing the page ensures that you're actually refreshing (in the case there is something funky happening on the client), but if this is not a concern for you, you can store that data in the history state with the history api directly (`history.replaceState(newState, document.title)`) and this will not have any adverse effect on the router. Alternatively you can use something like localStorage, sessionStorage, or indexedDb.

The reason there is no automatic copying from `with` to the history state is because the history state must be able to represented as json, and serializing/deserializing observables is out of the scope of the routing.
