### ISSUE TITLE
@profiscience/knockout-contrib-router-plugins-component is logging warnings.

### ISSUE THREAD

**Issue by gandrisl** [Profiscience/knockout-contrib#68]
Using this plugin and navigating through routes sometimes I get warning in console:

> [@profiscience/knockout-contrib-router-plugins-component] Unable to `new` viewModel. This may cause unexpected behavior. 

Is there a way to disable it? Or is it that I am doing something wrong that I get this warning?

**Comment by caseyWebb** [comment]
I've still got a _lot_ of documentation to write 😅

The component plugin has the following API (hopefully this doesn't just make things more confusing)...

```typescript
type MaybePromise<T> = T | Promise<T>

type DefaultImport<T> = { default: T }
type MaybeDefaultImport<T> = T | DefaultImport<T>

type Accessor<A, T> = (A) => T
type MaybeAccessor<A, T> = T | Accessor<A, T>

declare module '@profiscience/knockout-contrib-router' {
  interface IContext {
    component: MaybePromise<IRoutedComponentInstance>
  }

  interface IRouteConfig {
    component?:
      | MaybeAccessor<Context & IContext, MaybePromise<string>>
      | MaybeAccessor<Context & IContext, IAnonymousRoutedComponentConfig>
  }
}

export type IAnonymousRoutedComponentConfig =
  MaybePromise<{
    template: MaybePromise<MaybeDefaultImport<string>>
    viewModel?: MaybePromise<MaybeDefaultImport<IRoutedViewModelConstructor>>
    [k: string]: MaybePromise<any>
  }>

export interface IRoutedComponentInstance {
  viewModel?: any
}

export interface IRoutedViewModelConstructor {
  new(ctx: Context & IContext): any
}
```

Originally, this plugin only supported anonymous components. Using named components is experimental at the moment and needs 2 pain points addressed:

- ctx/params handled in a way that could be pretty confusing (not in line with the default router API).
- The router attempts to instantiate the viewModel itself and register it using `ko.components.register({ viewModel: { instance })` in order to attach it to `ctx.component.viewModel` for use by other plugins. (The init plugin does this, needs docs...) As I write this, I wonder if this could be done with named components as well with `ko.components.get` — something to play around with.

This all said, at the time being, this is the recommended usage:

```typescript
new Route('/', {
  // basic
  component: {
    template: 'Hello, World!',
    viewModel: class {
      constructor(ctx) { }
    }
  },

  // use an accessor
  component: (ctx) => ({
    template: 'Hello, World!',
    viewModel: class {
      constructor(ctx) { }
    }
  }),

  // implicit async accessor (promised values are resolved)
  component: (ctx) => ({
    template: import('./template.html'),
    viewModel: import('./viewModel')
  }),

  // explicit async accessor
  component: async (ctx) => ({
    template: await import('./template.html'),
    viewModel: await import('./viewModel')
  })
})
```

**Comment by gandrisl** [comment]
Thanks for such a fast reply :)
